services:
  redis:
    container_name: holiday-redis
    image: redis:7.4.0-alpine3.20
    ports:
      - 6379:6379
    networks:
      - overlay
  app:
    build: .
    ports:
      - 3000:3000
    networks:
      - overlay
    depends_on:
      - redis
    environment:
      HOST: 0.0.0.0
      NODE_ENV: production
      REDIS_URL: redis://holiday-redis:6379/0
networks:
  overlay:
